{% set name = "epic2" %}
{% set version = "0.0.42" %}
{% set hash_value = "3a17c9435a69ac1ea5ff0cf647dcde5734088cf668051be013ac2441a553abf3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build: 
  number: 0
  # Compilation errors on OSX
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - pysam
    - htslib
  run:
    - python
    - scipy
    - numpy
    - pysam
    - natsort
    - functools32 # [py27]
    - htslib

test:
  # Python imports
  imports:
    - epic2
  commands:
    - epic2 -h

about:
  home: http://github.com/endrebak/epic2
  license: MIT
  license_file: LICENSE
  summary: 'Ultraperformant Chip-Seq broad domain finder based on SICER.'
  
extra:
  identifiers:
    - doi:10.1093/bioinformatics/btz232
  recipe-maintainers:
    - endrebak
